title: "Olivia Fan Yiyun"
email: oliviafawn62@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello:) This is my portfolio website!
baseurl: "/" 
url: "/oliviafanyiyun.github.io" 
instagram_username: o1iv1a_
github_username: oliviafanyiyun

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
